
server:
  port: 8081

spring:
  datasource:
    username: root
    password: ab5051
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alltest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # formatSQL\u5F97\u8FD9\u6837\u5199
    properties:
      hibernate:
        format_sql: true
