server:
  port: 8081

spring:
  datasource:
    username: root
    password: ab5051
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alltest?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.songbo.mybatisplus.dao.domain