server:
  port: 8081
spring:
  datasource:
    username: root
    password: ab5051
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sign?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

  profiles:
    active: dev
