
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      shutdown-timeout: 0
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 500
        min-idle: 0
  datasource:
    username: root
    password: ab5051
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alltest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # formatSQL\u5F97\u8FD9\u6837\u5199
    properties:
      hibernate:
        format_sql: true
server:
  port: 8100

